### ISSUE TITLE
Issues in running cpbooster plugin on Vim on  a WSL configuration

### ISSUE THREAD

**Issue by itsameaditya** [searleser97/cpbooster#11]
I am Using WSL on windows 10 and recently started using the cpbooster plugin. After using `cpb clone` feature in the plugin, there was no issue while retrieving the sample cases from the website. But then when I typed the correct solution to the code (which got accepted on the ONLINE JUDGE) `cpbooster` still showed WA on my output .
Here is screenshot which describes it clearly:

The question link is : https://codeforces.com/problemset/problem/1525/C
My solution code is : https://pastebin.com/q0xuPE7N

### **_**Here it is clearly visible that I have got the correct output but the plugin shows WA on my code.**_**

![image](https://user-images.githubusercontent.com/73281787/118521349-9208fe00-b758-11eb-85e4-3e7fef84c323.png)

**Comment by searleser97** [comment]
Could you reproduce this with an **easier** problem (probably some A+B or something like that). Also could you add the URL of the problem you choose and your solution in code please ?

If this bug does not repro with an easier problem, then could you provide the URL of the problem that you used in your **issue** description ?

**Comment by searleser97** [comment]
The issue is that you are printing an **extra blank space** at the end of each line of your output. Codeforces trims each line (removes extra spaces), that is why codeforces accepts it as correct solution, but this is not true for other Online Judges.

`cpbooster` right now can only tell if you have extra leading or trailing blank spaces on the entire solution not line by line. I'll work on adding the feature for each line.
